# Generated by Django 5.0.8 on 2025-04-01 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0015_alter_comparison_compared_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['user', 'comparison_name'], name='filecompare_user_id_731424_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['similarity'], name='filecompare_similar_532bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['file1', 'file2'], name='filecompare_file1_i_d207b7_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'filename'], name='filecompare_user_id_0becf4_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at'], name='filecompare_uploade_98d397_idx'),
        ),
    ]
