# Generated by Django 5.0.8 on 2025-04-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0016_alter_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comparison',
            name='filecompare_user_id_731424_idx',
        ),
        migrations.RemoveIndex(
            model_name='comparison',
            name='filecompare_similar_532bc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='comparison',
            name='filecompare_file1_i_d207b7_idx',
        ),
    ]
