# Generated by Django 5.0.8 on 2025-04-04 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0017_remove_comparison_filecompare_user_id_731424_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cache_expiry', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('duplicate', 'Duplicate'), ('revision', 'Revision'), ('related', 'Related')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comparison',
            name='compressed_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='semantic_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tfidf_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='file',
            name='content_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, default='txt', max_length=10),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['similarity'], name='filecompare_similar_532bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['file1', 'file2'], name='filecompare_file1_i_d207b7_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['user', 'similarity'], name='filecompare_user_id_4b7ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_hash'], name='filecompare_content_a92035_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'file_type'], name='filecompare_user_id_bead92_idx'),
        ),
        migrations.AddField(
            model_name='comparisoncache',
            name='comparison',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='filecompare.comparison'),
        ),
        migrations.AddField(
            model_name='filerelation',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='filecompare.file'),
        ),
        migrations.AddField(
            model_name='filerelation',
            name='target_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='filecompare.file'),
        ),
        migrations.AddIndex(
            model_name='comparisoncache',
            index=models.Index(fields=['cache_key'], name='filecompare_cache_k_293142_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisoncache',
            index=models.Index(fields=['is_valid'], name='filecompare_is_vali_ffcd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisoncache',
            index=models.Index(fields=['cache_expiry'], name='filecompare_cache_e_1519af_idx'),
        ),
        migrations.AddIndex(
            model_name='filerelation',
            index=models.Index(fields=['relation_type'], name='filecompare_relatio_bd927f_idx'),
        ),
        migrations.AddIndex(
            model_name='filerelation',
            index=models.Index(fields=['source_file', 'relation_type'], name='filecompare_source__17a2f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filerelation',
            unique_together={('source_file', 'target_file', 'relation_type')},
        ),
    ]
