# Generated by Django 5.0.8 on 2025-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0018_comparisoncache_filerelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='full_match_lines_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison',
            name='no_match_lines_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison',
            name='partial_match_lines_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison',
            name='total_lines_count',
            field=models.IntegerField(default=0),
        ),
    ]
