# Generated by Django 5.0.8 on 2025-05-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0019_comparison_full_match_lines_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Duration of comparison in seconds'),
        ),
    ]
