# Generated by Django 5.0.8 on 2025-05-17 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecompare', '0020_comparison_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='avg_coverage',
            field=models.FloatField(default=0.0, help_text='Average coverage percentage'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='coverage1',
            field=models.FloatField(default=0.0, help_text='Coverage percentage for document 1'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='coverage2',
            field=models.FloatField(default=0.0, help_text='Coverage percentage for document 2'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='match_count',
            field=models.IntegerField(default=0, help_text='Total number of matching sentence pairs'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='weighted_similarity',
            field=models.FloatField(default=0.0, help_text='Weighted similarity score'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['coverage1'], name='filecompare_coverag_d5ebac_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['coverage2'], name='filecompare_coverag_1c481f_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['match_count'], name='filecompare_match_c_f2b760_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['weighted_similarity'], name='filecompare_weighte_898870_idx'),
        ),
    ]
